ALTER TABLE investments ADD COLUMN symbol VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE investments ADD COLUMN name VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE investments ADD COLUMN asset_type VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE investments ADD COLUMN currency VARCHAR(10) NOT NULL DEFAULT 'USD';
ALTER TABLE investments ADD COLUMN exchange VARCHAR(50) DEFAULT '';
ALTER TABLE investments ADD COLUMN maturity_date TIMESTAMPTZ;
ALTER TABLE investments ADD COLUMN yield_to_maturity DOUBLE PRECISION DEFAULT 0;
ALTER TABLE investments ADD COLUMN coupon_rate DOUBLE PRECISION DEFAULT 0;
ALTER TABLE investments ADD COLUMN network VARCHAR(50) DEFAULT '';
ALTER TABLE investments ADD COLUMN property_type VARCHAR(50) DEFAULT '';

DROP INDEX IF EXISTS idx_investments_security_id;
ALTER TABLE investments DROP COLUMN security_id;
