FROM golang:1.24

WORKDIR /app

# Install Air for hot reloading
RUN go install github.com/air-verse/air@latest

# We'll initialize modules in the container to avoid the go.sum issue
COPY go.mod ./
RUN go mod tidy

# Source code will be mounted as a volume
EXPOSE 8080

# Use air directly as the entrypoint
ENTRYPOINT ["air"]
